version: '3.8'

name: rtbs
services:
  web:
    container_name: rtbs_web
    build: ./src
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./src/application/:/usr/src/application/
    ports:
      - 8001:8001
    env_file:
      - ./.env
    depends_on:
      - database
    links:
      - database
  database:
    image: mysql:9.3.0
    container_name: rtbs_mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
  nginx:
    build: ./nginx
    container_name: rtbs_nginx
    volumes:
      - static_volume:/usr/src/application/static/:rw
      - media_volume:/usr/src/application/media/:rw
    ports:
      - 8081:8001
      - 8082:443
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  media_volume:
