version: '3.8'

name: rtbs
services:
  web:
    container_name: rtbs_web
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/application/:/usr/src/application/
    ports:
      - 8000:8000
    env_file:
      - ./src/application/.env.dev
    depends_on:
      - database
  database:
    image: mysql:9.3.0
    container_name: rtbs_mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_123456
      - MYSQL_DATABASE=rtbspythondb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p root_123456", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
