version: '3.8'

name: rtbs
services:
  web:
    container_name: rtbs_web
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/application/:/usr/src/application/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
    links:
      - database
  database:
    image: mysql:9.3.0
    container_name: rtbs_mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306

volumes:
  mysql_data:
