# Generated by Django 5.2.2 on 2025-06-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0003_tablebooking_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
