# Generated by Django 5.2.2 on 2025-06-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0004_tablebooking_end_time_tablebooking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
