# Generated by Django 5.2.2 on 2025-06-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0005_alter_tablebooking_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=False)),
                ('typeof', models.CharField(choices=[('increment', 'Increment'), ('session', 'Session')], max_length=25)),
                ('allow_reservation', models.BooleanField(default=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('increment_value', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
