# Generated by Django 5.2.2 on 2025-07-22 03:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0006_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('buffer_minutes', models.PositiveIntegerField(default=15)),
                ('max_bookings_per_slot', models.PositiveIntegerField(default=1)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablenum', models.CharField(max_length=250)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='table_id',
        ),
        migrations.AlterModelOptions(
            name='tablebooking',
            options={'ordering': ['-booking_datetime']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_datetime']},
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='allow_reservation',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='booking_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='booking_reference',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rtbsapp.timeslot'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='bookingdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='noofguest',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='rtbsapp.bookingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('session', 'start_datetime')},
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rtbsapp.restauranttable'),
        ),
        migrations.AddIndex(
            model_name='tablebooking',
            index=models.Index(fields=['booking_datetime'], name='rtbsapp_tab_booking_d451a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tablebooking',
            index=models.Index(fields=['status'], name='rtbsapp_tab_status_a2ef79_idx'),
        ),
        migrations.AddField(
            model_name='tableavailability',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rtbsapp.tablebooking'),
        ),
        migrations.AddField(
            model_name='tableavailability',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtbsapp.restauranttable'),
        ),
        migrations.AddField(
            model_name='tableavailability',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtbsapp.timeslot'),
        ),
        migrations.DeleteModel(
            name='Resturanttable',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='increment_value',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='label',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='typeof',
        ),
        migrations.AddIndex(
            model_name='tableavailability',
            index=models.Index(fields=['availability_date', 'is_available'], name='rtbsapp_tab_availab_8a69ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tableavailability',
            unique_together={('table', 'timeslot')},
        ),
    ]
