# Generated by Django 5.2.2 on 2025-07-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0007_bookingsession_restauranttable_tableavailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableavailability',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rtbsapp.restauranttable'),
        ),
        migrations.AlterField(
            model_name='tableavailability',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rtbsapp.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_datetime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_datetime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
