# Generated by Django 5.2.2 on 2025-07-23 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0008_alter_tableavailability_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='end_datetime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='start_datetime',
            new_name='start_time',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='rtbsapp.bookingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('session', 'start_time')},
        ),
    ]
