# Generated by Django 5.2.2 on 2025-07-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0009_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableavailability',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='rtbsapp.restauranttable'),
        ),
        migrations.AlterField(
            model_name='tableavailability',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='rtbsapp.timeslot'),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rtbsapp.restauranttable'),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rtbsapp.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeslots', to='rtbsapp.bookingsession'),
        ),
    ]
