# Generated by Django 5.2.2 on 2025-07-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0010_alter_tableavailability_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableavailability',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='rtbsapp.bookingsession'),
        ),
    ]
