# Generated by Django 5.2.2 on 2025-07-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0011_alter_tableavailability_availability_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableavailability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tableavailability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
