# Generated by Django 5.2.2 on 2025-07-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0013_timeslot_day_of_week_alter_tableavailability_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('session', 'start_time', 'day_of_week')},
        ),
    ]
