# Generated by Django 5.2.2 on 2025-07-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0014_alter_timeslot_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['-day_of_week', 'start_time']},
        ),
        migrations.AddField(
            model_name='tableavailability',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
    ]
