# Generated by Django 5.2.2 on 2025-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0015_alter_timeslot_options_tableavailability_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablebooking',
            options={},
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='table',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='rtbsapp.restauranttable'),
        ),
    ]
