# Generated by Django 5.2.2 on 2025-07-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0016_alter_tablebooking_options_bookingsession_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingsession',
            old_name='table',
            new_name='tables',
        ),
    ]
