# Generated by Django 5.2.2 on 2025-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0017_rename_table_bookingsession_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
