# Generated by Django 5.2.2 on 2025-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0018_alter_bookingsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='buffer_minutes',
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=120, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='max_bookings_per_slot',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
