# Generated by Django 5.2.2 on 2025-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0019_alter_bookingsession_buffer_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tableavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
