# Generated by Django 5.2.2 on 2025-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0020_alter_tableavailability_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebooking',
            old_name='postingdate',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
