# Generated by Django 5.2.2 on 2025-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0021_rename_postingdate_tablebooking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='bookingdate',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='bookingtime',
            field=models.TimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=120, null=True),
        ),
    ]
