# Generated by Django 5.2.2 on 2025-07-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtbsapp', '0022_alter_tablebooking_bookingdate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableavailability',
            unique_together={('table', 'timeslot', 'availability_date', 'start_time', 'end_time')},
        ),
    ]
